#pragma once

#include <Asset_Handle.hpp>
#include <ImageData.hpp>
#include <Primitive_Desc.hpp>

#include <cstdint>
#include <string>
#include <vector>

// Forward declarations: Gpu_Assets only stores references, so whoever
// includes this header (the application, through Engine_Context) does not
// pull in the Renderer or the Resource_Manager.
namespace ECS { struct Material_Component; }
namespace Renderer_System { class Renderer; }
namespace ResourceManager { class Resource_Manager; }

namespace EngineCore
{

    // Gpu_Assets: the single way to turn an asset request into something
    // drawable. Bridges ResourceManager (CPU side, Vulkan-agnostic) and the
    // Renderer (GPU side): each call does its CPU work in the resource
    // manager and its upload in the renderer, so the caller never handles a
    // gpu id and never has to remember an upload step.
    //
    // The methods state an intention (create a primitive, load an image,
    // create a material), not a step (load + upload + register). A cache hit
    // in the resource manager never uploads twice: the second caller finds
    // the gpu id already registered.
    //
    // Owns nothing: it borrows the resource manager and the renderer, so it
    // must be constructed after both and destroyed before them (declaration
    // order in Engine).
    class Gpu_Assets
    {
    public:

        Gpu_Assets(ResourceManager::Resource_Manager& _resources, Renderer_System::Renderer& _renderer);
        ~Gpu_Assets() = default;

        Gpu_Assets(const Gpu_Assets&) = delete;
        Gpu_Assets& operator=(const Gpu_Assets&) = delete;
        Gpu_Assets(Gpu_Assets&&) = delete;
        Gpu_Assets& operator=(Gpu_Assets&&) = delete;

        // Generates a primitive (or returns the cached one) and uploads it
        // if it has no gpu id yet.
        CoreTypes::Asset_Handle Create_primitive(const ResourceManager::Primitive_Desc& _desc);

        // Loads a glTF/GLB file (or returns the cached handles) and uploads
        // every primitive that has no gpu id yet. One handle per primitive.
        std::vector<CoreTypes::Asset_Handle> Load_mesh(const std::string& _path);

        // Loads an image (or returns the cached handle) and uploads it if it
        // has no bindless index yet. Throws if the file cannot be loaded.
        CoreTypes::Asset_Handle Load_image(const std::string& _path,
            CoreTypes::Pixel_Format _format = CoreTypes::Pixel_Format::RGBA8_SRGB);

        // (Move here the comment of Ensure_material_registered from Engine.hpp)
        // Stores the Renderer's material slot in _material.gpu_material_id
        // and returns it.
        uint32_t Create_material(ECS::Material_Component& _material);

        // Handle of the texture generated by the compute pass, usable as a
        // material's albedo. Registered on the first call and cached: the
        // resource manager does not deduplicate external images.
        CoreTypes::Asset_Handle Get_procedural_texture();

    private:

        uint32_t Ensure_mesh_uploaded(CoreTypes::Asset_Handle _mesh);
        uint32_t Ensure_image_uploaded(CoreTypes::Asset_Handle _image);

        ResourceManager::Resource_Manager& resources;
        Renderer_System::Renderer& renderer;

        CoreTypes::Asset_Handle            procedural_texture;
    };

} // namespace EngineCore