#pragma once

#include <vulkan/vulkan.h>

#include <Vulkan_Device.hpp>
#include <Vulkan_Handles.hpp>
#include <Vulkan_Image_Utils.hpp>

namespace Renderer_System
{

    // Vulkan_Depth_Resources: owns the depth buffer used for depth testing
    // (so closer objects correctly occlude farther ones when geometry
    // overlaps on screen). Manages the VkImage, its VMA allocation,
    // and the VkImageView that Vulkan_Framebuffer will reference.
    //
    // Unlike swapchain color images (one per swapchain image, since they
    // rotate), only ONE depth buffer is needed and shared across all
    // framebuffers - depth data from a previous frame doesn't need to be
    // preserved once that frame is done.
    //
    // The image and the view are owned by RAII members: a constructor that
    // fails after the image was created releases it, and the moves and the
    // destructor are the ones generated by the compiler. There is no
    // in-place resize: a swapchain recreation builds a complete new set of
    // targets (Swapchain_Targets) and swaps it in, so a failure leaves the
    // current depth buffer untouched.
    class Vulkan_Depth_Resources
    {
    public:
        // Creates the depth image, allocates its memory, and creates the
        // image view, sized to match the swapchain's current extent.
        // _depth_format: the depth format of the render pass the image is
        // attached through (Vulkan_Render_Pass::Get_depth_format), a
        // floating-point format chosen with the device
        // (Vulkan_Device::Get_depth_format).
        Vulkan_Depth_Resources(
            const Vulkan_Device& _device,
            VmaAllocator _allocator,
            VkFormat _depth_format,
            VkExtent2D _extent
        );

        ~Vulkan_Depth_Resources() = default;

        Vulkan_Depth_Resources(const Vulkan_Depth_Resources&) = delete;
        Vulkan_Depth_Resources& operator=(const Vulkan_Depth_Resources&) = delete;

        Vulkan_Depth_Resources(Vulkan_Depth_Resources&& _other) noexcept = default;
        Vulkan_Depth_Resources& operator=(Vulkan_Depth_Resources&& _other) noexcept = default;

        // The image view, needed by Vulkan_Framebuffer to attach this
        // depth buffer to each framebuffer it creates.
        VkImageView Get_image_view() const;

        // The format this depth buffer was created with.
        VkFormat Get_format() const;

    private:
        VkFormat depth_format;

        // Declared in creation order: the view is destroyed before the
        // image it looks at.
        Unique_Image     depth_image;
        Unique_Image_View depth_image_view;
    };

}
