#pragma once

#include <vulkan/vulkan.h>

#include <Vulkan_Device.hpp>
#include <Vulkan_Handles.hpp>
#include <Vulkan_Image_Utils.hpp>

namespace Renderer_System
{

    // Vulkan_Depth_Resources: owns the depth buffer used for depth testing
    // (so closer objects correctly occlude farther ones when geometry
    // overlaps on screen). Manages the VkImage, its VMA allocation,
    // and the VkImageView that Vulkan_Framebuffer will reference.
    //
    // Unlike swapchain color images (one per swapchain image, since they
    // rotate), only ONE depth buffer is needed and shared across all
    // framebuffers - depth data from a previous frame doesn't need to be
    // preserved once that frame is done.
    //
    // The image and the view are owned by RAII members: a constructor that
    // fails after the image was created releases it, and the moves and the
    // destructor are the ones generated by the compiler. Recreate builds a
    // complete replacement first and swaps it in, so a failure leaves the
    // current depth buffer untouched.
    class Vulkan_Depth_Resources
    {
    public:
        // Creates the depth image, allocates its memory, and creates the
        // image view, sized to match the swapchain's current extent.
        // _depth_format: a floating-point depth format chosen with the
        // device (Vulkan_Device::Get_depth_format).
        Vulkan_Depth_Resources(
            const Vulkan_Device& _device,
            VmaAllocator _allocator,
            VkFormat _depth_format,
            VkExtent2D _extent
        );

        ~Vulkan_Depth_Resources() = default;

        Vulkan_Depth_Resources(const Vulkan_Depth_Resources&) = delete;
        Vulkan_Depth_Resources& operator=(const Vulkan_Depth_Resources&) = delete;

        Vulkan_Depth_Resources(Vulkan_Depth_Resources&& _other) noexcept = default;
        Vulkan_Depth_Resources& operator=(Vulkan_Depth_Resources&& _other) noexcept = default;

        // Replaces the depth image/memory/view with ones of a new size. The
        // depth buffer must always match the swapchain's current extent
        // exactly, so this is called whenever the swapchain is recreated
        // (e.g. after a window resize). Strong guarantee: if the new
        // resources cannot be created, this object keeps the current ones.
        // Precondition: no command buffer pending execution uses the
        // current view (after the idle wait of Renderer::Recreate_swapchain).
        void Recreate(VkExtent2D _new_extent);

        // The image view, needed by Vulkan_Framebuffer to attach this
        // depth buffer to each framebuffer it creates.
        VkImageView Get_image_view() const;

        // The format this depth buffer was created with.
        VkFormat Get_format() const;

    private:
        // The constructor that does the work; the public one forwards the
        // device handle to it, and Recreate builds its replacement with it.
        Vulkan_Depth_Resources(
            VkDevice _device,
            VmaAllocator _allocator,
            VkFormat _depth_format,
            VkExtent2D _extent
        );

        VkDevice device_handle;

        // Replaces the Vulkan_Device back-pointer, which only existed to
        // call Find_memory_type() again inside Recreate().
        VmaAllocator allocator;

        VkFormat depth_format;
        VkExtent2D current_extent;

        // Declared in creation order: the view is destroyed before the
        // image it looks at.
        Unique_Image     depth_image;
        Unique_Image_View depth_image_view;
    };

}
